---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

- name: git-repo
  type: git
  source:
    uri: https://gitlab.ippon.fr/jparnaudeau/app-thales-paas
    branch: v1.0

- name: cf-dev
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: development
    space: {{cf-space}}
    skip_cert_check: true

- name: cf-qa
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: qa
    space: {{cf-space}}
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: production
    space: {{cf-space}}
    skip_cert_check: true

- name: git-pre-release
  type: github-release
  source:
    user: ebornier-pivotal
    access_token: {{access-token}}
    check: true
    repository: df-concourse
    include_source_tarball: true
    include_source_zip: true
    pre_release: true

- name: git-release
  type: github-release
  source:
    user: ebornier-pivotal
    access_token: {{access-token}}
    check: true
    repository: df-concourse
    include_source_tarball: true
    include_source_zip: true
    pre_release: false

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


jobs:

- name: analyze-repo
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: git-repo
    trigger: true
  - task: build
    file: git-repo/ci/analyze.yml

- name: analyze-pre-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: git-repo
  - get: git-pre-release
    trigger: true
  - task: build
    file: git-repo/ci/analyze.yml

- name: analyze-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: git-repo
  - get: git-release
  - task: build
    file: git-repo/ci/analyze.yml

- name: tests-repo
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: git-repo
    trigger: true
    passed: [ analyze-repo ]
  - task: build
    file: git-repo/ci/tests.yml

- name: tests-pre-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: git-repo
  - get: git-pre-release
    trigger: true
    passed: [ analyze-pre-release ]
  - task: build
    file: git-repo/ci/tests.yml

- name: tests-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: git-repo
  - get: git-release
    trigger: true
    passed: [ analyze-release ]
  - task: build
    file: git-repo/ci/tests.yml

- name: deploy-to-development
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: git-repo
    trigger: true
    passed: [ tests-repo ]
  - task: build
    file: git-repo/ci/build.yml
  - put: cf-dev
    params:
      manifest: build/manifest-dev.yml
      current_app_name: atp
      path: build/jhipster-sample-application-0.0.1-SNAPSHOT.jar
  - put: slack-alert
    params:
      channel: '#circle-of-code'
      text: |
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in development at https://atp.development.cfapps.alex.examples.cf

- name: deploy-to-qa
  public: true
  serial: true
  plan:
  - get: git-repo
  - get: git-pre-release
    trigger: true
    passed: [ tests-pre-release  ]
    params:
      include_source_tarball: true
  - task: build
    file: git-repo/ci/build-pre-release.yml
  - put: cf-qa
    params:
      manifest: build/manifest-qa.yml
      current_app_name: df-concourse
      path: build/df-concourse-0.0.1-SNAPSHOT.jar
  - put: slack-alert
    params:
      channel: '#circle-of-code'
      text: |
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in qa at https://df-concourse.qa.cfapps.alex.examples.cf

- name: deploy-to-prod
  public: true
  serial: true
  plan:
  - get: git-repo
  - get: git-release
    trigger: true
    passed: [ tests-release  ]
    params:
      include_source_tarball: true
  - task: build
    file: git-repo/ci/build-release.yml
  - put: cf-prod
    params:
      manifest: build/manifest-prod.yml
      current_app_name: df-concourse
      path: build/df-concourse-0.0.1-SNAPSHOT.jar
  - put: slack-alert
    params:
      channel: '#circle-of-code'
      text: |
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in production at https://df-concourse.production.cfapps.alex.examples.cf
